### ISSUE TITLE
Разработать документ реализации и фичу для проверки работоспособности данного документа

### ISSUE THREAD

**Issue by PiskunovSS** [PiskunovSS/BDD-1C-final-task#7]
Вынести процедуры загрузки фикстур в библиотеку и поправить фичу для проверки поступления, чтобы она тоже использовала функцию из бибилиотеки.

**Comment by PiskunovSS** [comment]
Разогнался я с созданием библиотечного сценария загрузки фикстур. Получается, что макеты нужно добавлять в библиотечную обработку проверки поведения, чтобы она их видела и могла загрузить. Или использовать внешние файлы, сложенные в каталоге \examples . Пока что нет времени переделывать. Поэтому уберу использование библиотеки ЭкспортныеСценарииДляПовторногоИспользования при загрузке фикстур.

**Comment by alehinsasha** [comment]
Есть возможность получать макет из обработки соответствующей выполняемой фиче.

**Comment by PiskunovSS** [comment]
Значит придется думать)

**Comment by PiskunovSS** [comment]
Фича реализована, загрузка фикстур библиотечной функцией тоже
